### ISSUE TITLE
One Config to Rule them All!

### ISSUE THREAD

**Issue by cobraz** [cobraz/pulumi-wordpress#5]
To make it easy to use this libray, we probably would want to have a simple interface that orchestrates a Wordpress, regardless of infrastructure-related stuff.

I imagine that we could have a config that looks something like this:

```typescript
const config = {
	projectName: 'thewebsite-com', // a URL safe name
	domain: 'thewebsite.com',
	databaseStorage: 10, // in gigabytes (minimum 10)
	activateBackup: true,
	size: 'small', // Must be either small, medium, large (presets)
};

... some code ...
```

If a user wants to control more than that, they need to utilize the underlying components.

@AnneMatilde how does that look for you?

**Comment by AnneMatilde** [comment]
That looks like a breeze @cobraz
